name: "Update Flake Packages ❄️"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 16 * * *"
  # these allow the workflow to show up when it's not on main yet
  pull_request:
  push:
    branches:
      - '**'
permissions:
  contents: write
  pull-requests: write

jobs:
  updateFlakePackages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Install Nix
        uses: cachix/install-nix-action@v31.5.2
      - name: Update flake packages
        #uses: selfuryon/nix-update-action@v1.1.0
        # this updates the nix-install-pkgs-action, older version no longer worked
        uses: gepbird/nix-update-action@95ce2cbe3360ba51481010d153fe5bc440413c03
        with:
          blacklist: "orb-forge-gui,mint-mod-manager,mint-mod-manager-no-hook"

