name: "Update Flake Packages ❄️"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 16 * * *"
  # these allow the workflow to show up when it's not on main yet
  pull_request:
  push:
    branches:
      - '**'
permissions:
  contents: write
  pull-requests: write
jobs:
  updateFlakePackages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Install Nix
        with:
          nix_path: "nixpkgs=https://github.com/NixOS/nixpkgs/archive/refs/heads/nixos-unstable.tar.gz"
        uses: cachix/install-nix-action@v31.5.2
      - name: Check <nixpkgs>
        run: "nix-instantiate --find-file nixpkgs"
      - name: Update flake packages
        uses: gepbird/nix-update-action@e66d1b0ec853a565b63a94c67aa56a3ca9097598
        with:
          blacklist: "orb-forge-gui"
