name: "Update Flake Packages ❄️"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 16 * * *"
  # these allow the workflow to show up when it's not on main yet
  pull_request:
  push:
    branches:
      - '**'
permissions:
  contents: write
  pull-requests: write
jobs:
  updateFlakePackages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Install Nix
        uses: cachix/install-nix-action@v31.5.2
        with:
          nix_path: "nixpkgs=https://github.com/NixOS/nixpkgs/archive/refs/heads/nixos-unstable.tar.gz"
      - name: Update flake packages
        #uses: gepbird/nix-update-action@v2
        uses: ./.github/actions/nix-update-action
        with:
          blacklist: "orb-forge-gui,mint-mod-manager-no-hook,mint-mod-manager"
